### ISSUE TITLE
Compile error: no matching function for call to ‘libcamera::ControlValue::set<libcamera::Span

### ISSUE THREAD

**Issue by mat100** [ayufan-research/camera-streamer#17]
Hi,

after the last system update of my RPi 4B (Linux xxx-xxx 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux), I can't compile anymore. The system is up to date and I am using the latest available version of camera-streamer (878ad95598a10e67f744666d4b66f741b49676f1)

![image](https://user-images.githubusercontent.com/3736719/188627685-596297e6-7dcc-4e7c-a7a7-6f58b51c1498.png)

Can you please advise/help me with the compilation?

**Comment by ayufan** [comment]
@mat100 Can you try now (latest master)?

**Comment by mat100** [comment]
Great, now everything works, thank you very much for the very quick help
