### ISSUE TITLE
libcamera is not supported

### ISSUE THREAD

**Issue by hadidon** [ayufan-research/camera-streamer#18]
Hello,

I tried this command on a RPi3A+ with the IMX477 camera (HQ):
`./camera-streamer -camera-path=/base/soc/i2c0mux/i2c@1/imx477@1a   -camera-type=libcamera   -camera-format=YUYV   -camera-width=4032   -camera-height=3040   -camera-fps=30   -camera-nbufs=2   -camera-high_res_factor=2   -camera-low_res_factor=4`

But I get the following response:
`device/libcamera/libcamera.cc: ?: libcamera is not supported`

I'm using the last Raspberry Pi OS version (32 bits) and the libcamera apps works well.

**Comment by ayufan** [comment]
@hadidon 

I think you don't have `libcamera-dev`. Can you do following?

```bash
apt-get install -y libcamera-dev
make clean
make
```
