### ISSUE TITLE
Compatibility with Libcamera Apps

### ISSUE THREAD

**Issue by hadidon** [ayufan-research/camera-streamer#19]
Hello,

After a fresh installation of Raspberry Pi OS and Camera-Streamer, I'm not able to use the Libcamera Apps anymore, I get:
`libcamera-hello: symbol lookup error: /lib/arm-linux-gnueabihf/libpreview.so: undefined symbol: _ZN9libcamera10ColorSpace4JpegE`

**Comment by ayufan** [comment]
@hadidon Unsure what you did install (and how), but it clearly seems that apps and libraries are not compatible with each other.
