### ISSUE TITLE
Fake Camera Sensor make Error

### ISSUE THREAD

**Issue by gallitim** [ayufan-research/camera-streamer#6]
Hello again,

I am running this on a different pi, but when I run the make command I get this error:

device/libcamera/fake_camera.c: In function ‘fake_camera_sensor’:
device/libcamera/fake_camera.c:18:34: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   18 |   struct media_v2_entity *ents = (struct media_v2_entity *)topology->ptr_entities;
      |                                  ^
cc1: all warnings being treated as errors
make: *** [Makefile:53: device/libcamera/fake_camera.o] Error 1
rm device/buffer_lock.o device/camera/camera_output.o device/buffer_queue.o http/http_h264.o device/buffer.o http/http_jpeg.o device/links.o opts/fourcc.o device/camera/camera_input.o device/camera/camera.o http/http.o http/http_ffmpeg.o ffmpeg/remuxer.o device/buffer_list.o device/dummy/buffer_list.o opts/log.o device/dummy/device.o device/dummy/dummy.o opts/control.o device/dummy/buffer.o http/http_methods.o device/camera/camera_isp.o opts/opts.o device/device.o

Can I still use the software with an imx219 sensor without this fake camera sensor? Or is there another way around this?
Thanks for the help.

**Comment by ayufan** [comment]
@gallitim Fixed with https://github.com/ayufan-research/camera-streamer/commit/8b1d066dfcd38a89f022a4a158e99a4feeb9d39c. It should work OOB without the need for `FAKE_CAMERA`. This is specific for `arducam_64mp` which is partially supported.
