### ISSUE TITLE
camera-options doesn't have any effect

### ISSUE THREAD

**Issue by henkyprayoga** [ayufan-research/camera-streamer#9]
I'm using camera-streamer to stream video from ov5647 sensor using libcamera. however, trying to do both horizontal and vertical flip doesn't work. even after i set the option. Please help. thank you

**Comment by ayufan** [comment]
Fixed with https://github.com/ayufan-research/camera-streamer/commit/a9c65fae0dad97fb5d4bc182ddf3ba4fbdb2cf92
